box.json.dist
fixtures/build/dir007/box.json
fixtures/build/dir007/test.php
src/Box.php
tests/Command/BuildTest.php

Create target directory if does not exists

---

Makefile

This allows to use Blackfire on Box building step to have a profile
reference in order to do performance optimisations in the future.

Add blackfire

---

src/Console/Command/Build.php
tests/Console/Command/BuildTest.php

Add "PHAR" to "size" to make it clear what is the subject.

Fix phrasing

---

.travis.yml
src/Configuration.php
src/Console/Command/Build.php
tests/ConfigurationTest.php

The path was not made relative to the base path which results in a file not found when box is executed in a different working directory than where the configuration file is.

Fix main script path registration

---

bin/box
src/functions.php
tests/bootstrap.php

Simplify the autoload script

---

README.md
UPGRADE.md
doc/configuration.md
src/Configuration.php
src/Console/Command/Build.php
src/FileSystem/file_system.php
src/Json/Json.php
tests/ConfigurationTest.php
tests/Console/Command/BuildTest.php
tests/Console/Command/ConfigurableTest.php
tests/Console/Command/ValidateTest.php
tests/Console/ConfigurationHelperTest.php

- Make main script mandatory (the value, not the setting)
- Configure `index.php` as the default main script
- Normalize the main script path
- Add documentation for the main script

Rework main script

---

src/Configuration.php
src/Console/Command/Build.php
tests/ConfigurationTest.php

Using symlinks in `files{-bin}` and `directories{-bin}` was causing an `InvalidArgumentException` error stating that the file/directory could not be found. When used with the Finder, the files were added but later when adding them to Box an error was occurring as the file could not be found.
Instead a more human-friendly error is now thrown and errors will occurs when the configuration will be loaded (not later).

Fix usage of symlinks

---

composer.json
composer.lock
doc/configuration.md
src/Box.php
src/Composer/ComposerConfiguration.php
src/Composer/ComposerOrchestrator.php
src/Configuration.php
src/FileSystem/file_system.php
tests/BoxTest.php
tests/Composer/ComposerConfigurationTest.php
tests/ConfigurationTest.php

Exclude dev dependencies

---

.travis.yml
Makefile
bin/box
composer.json
src/Box.php

Fix usage of Box when installed globally

---

src/Configuration.php
src/Console/Command/Compile.php

For now this mode is quite minimalist but it should prove to more useful in the future to allow unsigned PHAR for development purposes for example.

Add a dev mode

---

doc/configuration.md
src/Configuration.php
tests/ConfigurationTest.php

- Update the documentation
- Remove the related TODOs

Fix metadata

---

README.md

According to the upgrade file, this has been removed from the library.

Update the list of features of the library

---

fixtures/build/dir000/test-symlink.php
fixtures/build/dir000/unknown
src/Configuration.php

Ignore symlinks

---

src/Configuration.php
tests/ConfigurationTest.php
tests/Console/Command/CompileTest.php

Do not include the existing PHAR when collecting the files

---

Makefile

This avoids the command to become a rule accidentaly

Add PHONY targets

---

composer.json
composer.lock

Update Composer XdebugHandler

---

src/Console/Command/Compile.php
src/bootstrap.php

Check for the memory limit setting and bumpts it to `512M` when lower than that or to
`BOX_MEMORY_LIMIT` if that environment variable is defined.
Closes #179

Bump the memory limit

---

src/Console/Command/Compile.php

I really need to add a test for checking this at some point

Fix type error

---

bin/box
requirement-checker/bin/check-requirements.php

Add the check to both the Box entry point and the requirement checker.
Closes #159

Allow the application to be run only from the CLI

---

src/Console/Command/Compile.php
tests/ConfigurationTest.php
tests/Console/Command/CompileTest.php

Display the file permission in the octal form

---

Makefile
src/Console/Command/Build.php
src/Console/Command/Compile.php
src/PhpSettingsHandler.php
tests/ConfigurationFileTest.php
tests/ConfigurationTest.php
tests/ConfigurationTestCase.php

Automatically adjust the ulimit for the compression

---

README.md
doc/configuration.md
res/schema.json
src/Configuration.php
src/Console/Command/Compile.php
tests/ConfigurationTest.php

Add a dump autoload configuration setting

---

src/Composer/ComposerOrchestrator.php
tests/BoxTest.php

Fail with a comprehensible RuntimeException.

Gracefully fail when the autoloader could not be dumped

---

src/Console/Command/Compile.php
tests/Console/Command/CompileTest.php

Display the number of files included in the PHAR

---

.travis.yml
composer.json
composer.lock

Closes #212
Also ensure the proper dependencies are used when updating Box in the CI.

Fix the invalid Composer JSON files

---

box.json.dist
composer.json
composer.lock
src/Console/Application.php
tests/Console/ApplicationTest.php
tests/Console/Command/CompileTest.php

Always displays the version and when in the PHAR add the release date.

Add the application pretty version

---

src/Configuration.php
tests/ConfigurationTest.php

This would ideally also need some tests..

Fixed Scoper custom path configuration option

---

README.md
UPGRADE.md
doc/configuration.md

Add missing documentation

---

box.json.dist
src/Configuration.php
tests/ConfigurationFileNoConfigTest.php
tests/Console/Command/CompileTest.php
tests/RequirementChecker/RequirementsDumperTest.php

Do not exclude the license files

---

README.md
box.json.dist
src/Configuration.php
tests/ConfigurationTest.php
tests/Console/Command/CompileTest.php

Sets the permissions to 755 by default

---

.github/tap-release.yml

Add tap release configuration

---

doc/configuration.md
res/schema.json
src/Configuration.php
tests/ConfigurationFileTest.php
tests/Console/Command/CompileTest.php

Add a force auto-discovery mode

---

.travis.yml
src/Console/Command/Compile.php
src/Console/Command/Diff.php
src/Console/Command/Info.php
src/Console/Command/Process.php
src/Console/Command/Validate.php
src/Console/Command/Verify.php
src/Console/Logger/CompileLogger.php
src/Console/MessageRenderer.php
tests/Console/ApplicationTest.php
tests/Console/Command/CompileTest.php
tests/Console/Command/ProcessTest.php
tests/Console/Command/ValidateTest.php
tests/Console/Command/VerifyTest.php

- Make a few messages more readable or friendly
- Add the validation step to the CI

Make some UI tweaks

---

doc/configuration.md
src/Configuration.php
tests/ConfigurationTest.php
tests/Console/Command/GenerateDockerFileTest.php

Add the timezone to the default date format

---

src/Configuration.php
tests/ConfigurationTest.php

Add a recommendation as expected when the `compression` setting is set to its default value

---

src/Configuration.php
tests/ConfigurationFileNoConfigTest.php
tests/ConfigurationFileTest.php
tests/ConfigurationSigningTest.php
tests/ConfigurationTest.php

The blacklisting was misconfigured causing the blacklisting of any file or directory containing the
name of the main script.
Closes #303

Fix blacklisting of the main script

---

src/Box.php
src/Configuration.php
tests/ConfigurationFileNoConfigTest.php

Fix the auto-discovery of files with empty paths for PSR-0 autoloaders

---

.gitignore
Makefile
fixtures/build/dir011/src/Y.php
scoper.inc.php
src/Configuration.php

Add support for PhpScoper files whitelisting

---

src/Configuration.php
tests/ConfigurationTest.php

Add a deprecation message when the legacy compactors are being used

---

bin/box

Allow Box to run with a `embed` SAPI

---

src/Configuration.php
tests/ConfigurationFileNoConfigTest.php
tests/ConfigurationFileTest.php

Exclude the generated artefact from the collected files

---

.travis.yml
tests/DocumentationSchemaTest.php

Add PHP 7.3 to the CI

---

src/DockerFileGenerator.php
tests/DockerFileGeneratorTest.php

Add PHP 7.3 image to the Dockerfile generator

---

scoper.inc.php

Fix the PHP 7.1 polyfill autoloading issue

---

src/Console/Command/Compile.php
tests/Console/Command/CompileTest.php

Add the following elements:
- the PHP version used
- the PHP extension loaded
- the command being used to build the PHAR
- the Box version
Closes #385

Add more information to the dumped configuration

---

src/Console/Command/Process.php
tests/Console/Command/ProcessTest.php

Dump the whitelist

---

src/Console/Command/Diff.php
tests/Console/Command/DiffTest.php

Fix the diff command

---

requirement-checker/scoper.inc.php

Update the requirement checker PHP-Scoper configuration

---

requirement-checker/expected_terminal_diff
requirement-checker/src/Terminal.php
requirement-checker/tests/IOTest.php
scoper.inc.php
tests/Console/Command/CommandTester.php
tests/Console/Command/CompileTest.php
tests/PhpScoper/DummyScoper.php
tests/PhpScoper/SerializablePhpScoperTest.php

Attempt to fix CI

---

composer.json

See https://github.com/box-project/box/pull/472#discussion_r486867050

Put back symfony/phpunit-bridge

---

src/Composer/ComposerOrchestrator.php
tests/Console/Command/CompileTest.php

Forward BOX_ALLOW_XDEBUG to Composer

---

.requirement-checker/vendor/composer/ClassLoader.php

See: https://github.com/composer/composer/commit/fc961dce707aeb52ba76d95253d7d70689cfbd84

Backport fix from Composer

---

src/DockerFileGenerator.php
tests/DockerFileGeneratorTest.php

Hoping this works, I can't seem to get the tests to pass locally as it prompts for editor input. It looks like all builds passed on CI, except for one (https://travis-ci.org/github/box-project/box/builds/743917614).

Add PHP 7.4 image to the Dockerfile generator

---

doc/symfony.md

Update symfony doc to explain the changes in the project dir

---

.requirement-checker/vendor/composer/autoload_real.php
composer.json
requirement-checker/composer.json
tests/Console/Command/CompileTest.php
tests/RequirementChecker/RequirementsDumperTest.php

Fix for #520, and maybe for #489 too.
Of course it would be better to have a test demonstrating what the issue was.

Disable Composer platform-check in requirement-checker

---

composer.json
composer.lock

paragonie/pharaoh 0.5.x does not allow php 8.0, preventing installation of humbug/box in php 8 environments.

Allow paragonie/pharaoh ^0.6

---

res/schema.json

See #531; not an exhaustive list

likely invalid output paths

---

.github/workflows/build.yml
requirement-checker/scoper.inc.php

use git for retrieving the lastest tag version

---

doc/configuration.md

Fix issue #576 by important note in documentation

Solve scope of metadata callback by documentation

---

src/DockerFileGenerator.php
tests/DockerFileGeneratorTest.php

Add PHP 8.0 and 8.1 to DockerFileGenerator

---

src/Console/Command/Diff.php

Review Diff command

---

src/Console/Command/Extract.php

Review Extract command

---

src/Console/Command/Compile.php
src/Console/Command/GenerateDockerFile.php

Review GenerateDockerFile command

---

src/Console/Command/Process.php

Review Process command

---

src/Console/Command/Info.php

Review Info command

---

src/Console/Command/Verify.php

Review the Verify command

---

bin/box
src/Console/Command/BaseCommand.php
src/Console/IO/IO.php
src/Console/OutputFormatterConfigurator.php
tests/Console/Command/ValidateTest.php

Extract output formatter configuration from the base command

---

src/Console/Command/ChangeWorkingDirOption.php
src/Console/Command/Compile.php
src/Console/Command/Process.php

Make ChangeableWorkingDirectory trait an input option utility

---

doc/configuration.md

Add warning that setting the directory or finder key disables file autodiscovery unlessed forced

---

doc/configuration.md

Add doc about the files ignored for the directories clause

---

doc/configuration.md
src/Configuration/Configuration.php

Add warning about symlinks

---

README.md
doc/faq.md
doc/symfony.md

This hopefully allows to fit a bit more random information.
Closes #519

Add FAQ section

---

mkdocs.yaml

Remove deplicate entry.

---

Makefile
requirement-checker/Makefile

More rules will be move from the root to the requirement-checker Makefile later.

chore(requirement-checker): Add a Makefile

---

.github/workflows/lint.yaml
.github/workflows/requirement-checker.yaml
.github/workflows/unit-tests.yaml
Makefile
requirement-checker/Makefile
requirement-checker/composer.json

ci(requirement-checker): Add a dedicated workflow for the requirement

---

src/Configuration/Configuration.php
src/PhpScoper/SerializableScoper.php

Remove the need of the PHP-Scoper hotfixes.

fix: Fix the PHP-Scoper incompatibilities

---

.github/workflows/unit-tests.yaml
tests/Console/Command/InfoTest.php

Extracted those changes from @SamMousa in https://github.com/box-project/box/pull/707.
Co-authored-by: Sam Mousa <sam@mousa.nl>

test: Add missing @requires bz2 annotations 

---

tests/Configuration/ConfigurationTest.php

Extracted from #707.
Co-authored-by: Sam Mousa sam@mousa.nl

chore: Make git based configuration test more reliable

---

src/Console/Command/Info.php
tests/Console/Command/InfoTest.php

fix: Remove unused metadata option

---

.github/workflows/e2e-tests.yaml
.github/workflows/requirement-checker.yaml

This is an attempt at reducing the rate limit hits.

ci: Reduce the number of API calls made

---

src/RequirementChecker/PackageInfo.php
tests/RequirementChecker/PackageInfoTest.php

fix: Fix the extension name used for the requirements for Zend OPcache

---

fixtures/build/dir013/bin/run
fixtures/build/dir013/composer.json
fixtures/build/dir013/composer.lock

test: Make the ComposerInstalledVersions e2e test reliable

---

src/Console/Command/Extract.php

Expose the paths: they will be needed from Pharaoh.

refactor: Expose the PHAR meta dumped files in the extract command

---

src/Composer/ComposerOrchestrator.php

fix: Show more information upon failure when getting Composer version

---

src/Console/Command/Compile.php

fix: Correctly close the info tag

---

doc/faq.md

doc: Add a doc entry to help out the case when the shipped PHAR contains Box

---

README.md
doc/docker.md
doc/reproducible-builds.md
doc/symfony.md

doc: Add documentation for reproducible builds

---

src/Composer/ComposerOrchestrator.php
src/Composer/ComposerProcessFactory.php

The verbosity (and ANSI/no-ANSI) of the IO should not inpact those processes.

fix: Fix the ComposerOrchestrator in quiet verbosity

---

src/Composer/ComposerProcessFactory.php

`ComposerProcessFactory` which was introduced in #1082 should not have been made eager loaded. Not all Box compilations require Composer and changing that would make Box fail when no Composer binary can be found.

fix: Make the ComposerProcessFactory lazy

---

src/Configuration/Configuration.php

Fix bad merge of #1100 which should have been adapted after #1106.

test: Fix signing algorithm comparison

---

doc/phar-signing.md

Address the various comments made by @theseer in #1096.

doc: Improve the signing docs

---

tests/Composer/BaseComposerOrchestratorComposerTestCase.php
tests/Composer/ComposerOrchestratorComposer22TestCase.php
tests/Composer/ComposerOrchestratorComposer23TestCase.php
tests/Composer/ComposerOrchestratorComposer24TestCase.php

In #1082 the test cases where incorrectly refactored making them share the same condition.

test: Fix the Composer orchestrator integration tests

---

.github/workflows/requirement-checker.yaml

See https://github.com/humbug/php-scoper/pull/895.

ci: Leverage the git diff option

---

composer.json
composer.lock

Revert "build: Remove unused extensions requirements and packages"

---

src/Test/FileSystemTestCase.php

test: Rename the temporary directory from Box into BoxTest

---

src/Console/Command/Compile.php

Fixes the error introduced in #1190.

fix: Correctly interpret the parallelization option

---

src/Console/Command/GenerateDockerFile.php
tests/Console/Command/GenerateDockerFileTest.php

feat: Allow to pass a `--working-dir` option to the docker command

---

src/Composer/Artifact/DecodedComposerJson.php
src/Composer/Artifact/DecodedComposerLock.php
src/Composer/Package/Extension.php
src/Composer/Package/Extensions.php
src/Composer/Package/PackageInfo.php
src/Composer/Package/RequiredItem.php
src/Composer/Throwable/InvalidExtensionName.php
src/RequirementChecker/AppRequirementsFactory.php
tests/Composer/Artifact/DecodedComposerJsonTest.php
tests/Composer/Artifact/DecodedComposerLockTest.php
tests/Composer/Package/ExtensionTest.php
tests/Composer/Package/ExtensionsAssertion.php
tests/Composer/Package/PackageInfoTest.php
tests/Composer/Package/RequiredItemTest.php

refactor: Introduce a Extension value object

---

src/Composer/Artifact/DecodedComposerJson.php
src/Composer/Artifact/DecodedComposerLock.php
src/Composer/ComposerConfiguration.php
src/Configuration/Configuration.php
src/Console/Command/Compile.php
tests/Composer/ComposerConfigurationTest.php

- Move some of the work done by `ComposerConfiguration` to the respective artifact classes
- Leverage the artifact classes `DecodedComposerJson` and `DecodedComposerLock` in `ComposerConfiguration`

refactor: Leverage the Decoded Composer artifiacts for the ComposerConfiguration helper

---

src/Configuration/Configuration.php

The tests will be covered by #1288.

fix: Pick the correct custom vendor-dir config

---

composer.json
composer.lock

feat: Allow sebastian/diff 6.x and 7.x
