bin/box

Fix https://github.com/box-project/box2/pull/164

Fix usage when installed with GCR

---

Makefile
bin/box
src/Application.php
src/Box_Extract.php
src/Command/Info.php
src/Command/Verify.php
src/Signature.php
src/StubGenerator.php
tests/Command/VerifyTest.php
tests/ExtractTest.php
tests/StubGeneratorTest.php
tests/bootstrap.php

Fix an issue with the `Extract` class which should not be namespaced neither autoloaded.
Also remove the checks of wether or not the PHAR extension is loaded. The extension is present by default since PHP 5.3 so I don't think we should care for now at least.

Fix the PHAR building

---

src/Command/Build.php
src/Configuration.php
src/functions.php
tests/Command/BuildTest.php
tests/ConfigurationTest.php

Closes #6
Add the following elements to the logs when building a PHAR:
- Time & memory usage
- Size of the built PHAR
- The metadata content
- The file permissions used
As well as some tweaks for the log messages.

Add more information to logs when building PHAR

---

src/Box.php
src/Command/Build.php
tests/Command/BuildTest.php

Harden the tests:
- Check the PHAR files when building in order to test if the mapping is
working as expected
- Added tests when using Box stub, the default stub or a custom stub
- Fixed an issue when using the default stub: still register the main
script as the cli & web index script when provided

Harden stub tests

---

src/Command/Build.php
src/Configuration.php
src/MapFile.php
src/RetrieveRelativeBasePath.php
tests/ConfigurationTest.php

Paves the way for #32.
As it stands, #32 requires some functions from `Configuration` which would require `Configuration` to be serializable. This is a lot of work so it makes sense to rather encapsulate some behaviour in utility classes and leverage them instead. As a result only those utility classes would require to be serializable which is trivial.
This also prepares a change for the `Box` class which IMO should handle the file mapping as it already handles the placeholders replacement and compactor processing.

Refactor configuration to leverage utility classes

---

Makefile

Include dev dependencies in the PHAR. Although less realistic for a real
usage of box, this allows us to benchmark a bigger PHAR which is more
relevant.
Also make use of the quiet mode to avoid any logging which could cause
more unecessary IO.

Tweak Blackfire config

---

fixtures/Compactor/FakeCompactor.php
fixtures/build/dir000/binary
src/Box.php
src/Command/Build.php
src/Configuration.php
src/RetrieveRelativeBasePath.php
tests/BoxTest.php
tests/Command/BuildTest.php
tests/ConfigurationTest.php

Moves the handling of the mapping from the `Build` command to `Box` during the `addFile()`. The `addFile()` command has also been refactored to be able to:
- Add files with a different content than the one found in the file (e.g. for the main script)
- Add binary files (which should not be compressed and neither have their placeholder replaced)

Refactor usage of addFile

---

src/Command/Build.php
src/Command/ChangeableWorkingDirectory.php
tests/Command/BuildTest.php

Add the option `working-dir|d` to the `build` command in order to execute the build command from a different directory.

Add working-dir option

---

composer.json
src/Box.php
tests/Command/BuildTest.php

The process of adding files with Box works like the following:
- Collect all the files to add with `Configuration`
- Add the files to `Box
- Find the path that will be used to add the file to the PHAR
- Replace the placeholder values
- Runs the compactors on the file content
- Add the file to the PHAR
There is two expansive processes here:
- collecting the files
- processing the file contents
The first one is out of scope of this PR, but this PR address the second point which is reducing the processing time by parallelising this work.
---
Note for myself: extract from this PR building files from an iterator/array of files which will drastically simplify this PR.

Process files in parallel

---

bin/box
src/Box_Extract.php
src/Console/ConfigurationHelper.php
tests/Console/ConfigurationHelperTest.php
tests/bootstrap.php

Remove the existence of the constants. They are useful to change the paths used for box even when it is used from the PHAR, but it easily leads to wtf situations I don't really want to deal with for now.

Remove usage of string constants

---

.php_cs.dist
TODO
composer.json
src/Box.php
src/Console/Command/Build.php
src/FileSystem/FileSystem.php
src/Test/CommandTestCase.php
src/Test/FileSystemTestCase.php
tests/BoxTest.php
tests/ConfigurationTest.php
tests/Console/Command/BuildTest.php
tests/Console/ConfigurationHelperTest.php
tests/ExtractTest.php
tests/Verifier/OpenSslTest.php
tests/Verifier/PublicKeyTest.php

Although this patch contains a couple of other things, the main change here is how the files are added.
Indeed right now the current process is to process the contents of the files in parallel and then add them one by one to the PHAR.
Instead, this new approach will dump all of those files in a temporary location to take advantage of the `Phar::buildFromDirectory()` method which seems to be order of magnitudes more performant. The result is a **70 to 80% speed improvement**.
Other changes:
- Add a missing rule to PHP-CS-Fixer to get rid of unused use statements
- Adjust PHP-CS-Fixer list config to use the short syntax instead of the
long one
- Exclude the tests classes (not test cases) from the non-dev code
- Create a new TestCase class to deal with temporary directories
- Register the …

Dump files instead of adding strings

---

src/Configuration.php
src/Console/Command/Build.php
src/FileSystem/FileSystem.php
src/MapFile.php
tests/ConfigurationTest.php

In some cases it was more convenient to get the directory path with an ending slash e.g. `dir/`. To achieve that the `canonicalize` function was "hacked", i.e. instead of being a simple proxy to `Path::canonicalize()` it was doing some extra stuff to keep that ending slash.
However this make the `canonicalize` function incorrect. Instead the issue has been fixed at its core: `canonicalize` behaves in a more "standard" way and cases where the ending slash is required are fixed.

Fix canonicalize

---

src/Console/Command/Build.php
tests/Console/Command/BuildTest.php

When the default stub is used, Box was trying to register an alias to the PHAR. However the alias cannot be null or it results in a fatal error.

Fix alias usage with stub generation

---

src/Console/Command/Build.php

- Remove the verbosity check: the only verbosity remaining is `quiet` in which case the `$io` won't print anything
- Remove no file exist check: since the Configuration cannot be created with an empty flag anymore this line is no longer reachable

Remove dead code

---

src/Box.php
src/Console/Command/Compile.php
src/functions.php

As of now the closure serialization used for `parallelMap()` does not work with breakpoints. As such
it is very hard to debug the `$processFile` callable. This new debug mode allow to replace the
`parallelMap()` call by a regular `array_map()`.

Add debug mode

---

src/Compactor/PhpScoper.php
tests/Compactor/PhpScoperTest.php

Return the content of the file unchanged when the scoping fails.

Make scoping tolerant to failure

---

README.md
UPGRADE.md
doc/configuration.md
res/schema.json
src/Configuration.php
tests/ConfigurationTest.php

- No longer accept a string value for the `compactors` setting
- No longer accept a numerical value for the `algorithm` and `compression` settings
- Allow `null` for the `algorithm` and `compression` settings
- Rework the documentation for `chmod`, `compactors`, `compression` and `algorithm`

Review some parameters

---

UPGRADE.md
src/Console/Command/Info.php
tests/Console/Command/InfoTest.php

- Remove support for TAR and ZIP based PHARs: I have no idea how to create one and neither is there any tests for it
- Remove the metadata option: it is always shown
- When no metadata is found, the metadata displayed is `None`
- Display the number of files found in the PHAR
- Display the weight of the PHAR
- Display compression `[NONE]` when no compression is found
- The compression is now properly calculated instead of relying on `Phar::isCompressed()` which returns the wrong result when the default PHAR is not used
- A percentage of the compression listed is used when multiple compression or partial compression is used

Tweak the info command

---

UPGRADE.md
bin/box
src/Composer/ComposerOrchestrator.php
src/Console/Command/Compile.php
src/Console/Command/Info.php
tests/Console/Command/InfoTest.php

- No longer depend on the Composer Application to instantiate the Composer class
- No longer dump a `scoper-autoload.php` file and instead append the whitelist statements to
`autoload.php`

Rework the Composer Orchestrator

---

doc/configuration.md
src/Configuration.php
tests/ConfigurationTest.php

Fix the blacklist usage

---

composer.json
composer.lock
src/Box.php
src/Configuration.php
src/Console/Command/Compile.php
src/functions.php
tests/ConfigurationTest.php

Debug mode now dumps all the files (the binary files were currently not included). The handling of
the dump has been changed a bit as well: the previous dumped files are now removed in `Compile`
which is more natural and less hacky than in `Box::addFile()`.
The configuration file is dumped as well to ease debugging.
The verbosity is forced to debug when the debug mode is enabled.
Closes #102

Dump all files in debug mode

---

fixtures/PhpScoper/FakePhpScoper.php
src/Box.php
src/Compactor/PhpScoper.php
src/Composer/ComposerOrchestrator.php
src/Configuration.php
src/PhpScoper/NullScoper.php
src/PhpScoper/Scoper.php
src/PhpScoper/SimpleScoper.php
src/functions.php
tests/Compactor/PhpScoperTest.php
tests/Console/Command/InfoTest.php
tests/PhpScoper/NullScoperTest.php
tests/PhpScoper/SimpleScoperTest.php

Add an adapter for PHP-Scoper which:
- Removes the dependency on the configuration API
- Simplify the scoping signature
- Avoid to pass around the whole PHP-Scoper config
The new integration also ensure the scoping is done with a random prefix.

Simplify PhpScoper integration & Make the scoping prefix unique

---

Makefile
src/Box.php
src/Composer/ComposerConfiguration.php
src/Composer/ComposerOrchestrator.php
src/Configuration.php
src/Console/Command/Compile.php
src/Json/Json.php
tests/BoxTest.php
tests/Composer/ComposerConfigurationTest.php
tests/ConfigurationTest.php

- Make the `composer.json` and `composer.lock` file paths accessible from the configuration
- Make the decoded contents of those two files accessible from the configuration
- One file does not require the other
- Neither of those files are mandatory but when they are found, they must be valid
- Refactored the `ComposerConfiguration` to leverage the new API
- The autoloader can now be dumped when adding non-binary files to Box provided the `composer.json` file is given
- Always include the `composer.json` and `composer.lock` files to the added files whenever possible

Expose Composer JSON & Lock file contents

---

fixtures/build/dir009/box.json
fixtures/build/dir009/index.php
fixtures/build/dir009/main.php
src/Console/Command/Compile.php
tests/Console/Command/CompileTest.php

Add a `--no-config` option for the `compile` command which allows to completely ignore any
configuration file found.

Add a no config option for `compile`

---

.gitignore
Makefile
bin/box
fixtures/build/dir010/box.json
fixtures/build/dir010/index.php
fixtures/build/dir010/scoper.inc.php
scoper.inc.php
src/FileSystem/file_system.php
src/bootstrap.php
src/functions.php
tests/Console/Command/CompileTest.php
tests/bootstrap.php

Even though the isolated PHP-Scoper is not used per se (Box does not use the `finders` key from 
`scoper.inc.php` file), the class will still be loaded and as such requires to be registered.

 Fix PHP-Scoper isolated finder not found

---

src/Box.php
tests/BoxTest.php

When adding a binary file with a given content, the content was wrongly discarded in favour of the
file contents if the file existed.

Fix adding a binary file with a different content that the existing file

---

src/Box.php
src/Console/Command/Compile.php
src/functions.php

- Instead of dumping the files as they are added to the PHAR in debug mode, the code of the PHAR is
simply extracted at the end of the compilation process to the debug directory
- A new `--no-parallel` option has been added to the `compile` command to not process the files in
parallel instead of doing so only in debug mode
- A new `--no-restart` option has been added to the `compile` command to not restart the PHP process
allow more easily to keep xdebug enabled
- The verbosity is now forced to debug ealier when the debug mode is enabled. This ensures the new
verbosity set applies to the process restart check

Make compilation faster in debug mode and added new compilation options

---

src/Configuration.php
tests/ConfigurationTest.php

If using multiple finders each with appends, some of the files were omitted because they had the
same index.

Fixed missing files when using multiple append

---

src/Configuration.php
tests/ConfigurationTest.php

The `bin` entry in the `composer.json` can be a `string` besides a `string[]`.

Fix main script failure when bin is a string

---

bin/box
doc/configuration.md
src/Configuration.php
src/bootstrap.php
tests/ConfigurationFileTest.php
tests/Console/Command/CompileTest.php

Since the main script requires some special processing and is added before the regular and binary
files, it should not be included in the regular or binary files.
This was actually the case when the main script was included via `files`, `files-bin` and `append`
(from `finder` or `finder-bin`). The main script path is now properly excluded in such cases.
Closes #168

Fix the main script inclusion

---

src/Box.php
tests/BoxTest.php
tests/Console/Command/CompileTest.php

Starting Amp has an overhead and increase the likelyhood of rising an issue due to how Amp works. As
a result, it is better to not have to start it unless necessary. So far the current compactors are
fast enough to not require parallel processing, the build from Box without PHP-Scoper goes from 5s
with parallel processing to 3s without.
Closes #135

Start Amp only if PHP-Scoper is used

---

src/Console/Command/Compile.php
src/RequirementChecker/AppRequirementsFactory.php
src/RequirementChecker/RequirementsDumper.php
tests/RequirementChecker/AppRequirementsFactoryTest.php

When a PHAR is compressed, it also requires the PHP extension `zip`.
Closes #164

Fix PHAR minimal requirements

---

.php_cs.dist
bin/box
requirement-checker/src/Checker.php
requirement-checker/src/IO.php
requirement-checker/src/Requirement.php
requirement-checker/src/RequirementCollection.php
src/Configuration.php
tests/ConfigurationFileNoConfigTest.php

If the files/directories directly collected from the `composer.json` are not excluded, the finder
blacklist will not be able to operate on it.
This was already accounted for the blacklisted files but was not applied to the directories.

Apply the blacklist to the retrieved directories from the composer.json

---

src/Box.php
src/Console/Command/Build.php
src/Console/Command/Compile.php
src/PhpSettingsHandler.php
tests/BoxTest.php
tests/ConfigurationFileTest.php
tests/ConfigurationTest.php
tests/ConfigurationTestCase.php
tests/Console/Command/CompileTest.php

No longer rely on the exposed PHAR by the Box class and instead introduce a new API. The new API is meant to keep all the added files in memory and add them to the PHAR in one shot at the very end.
This will make it easier to decide whether or not the autoload should be dumped and no longer worry about the order in which the files are added regarding the autoload.

Refactor the way files are added to the PHAR

---

README.md
doc/configuration.md
src/Configuration.php
src/Console/Command/Build.php
src/Console/Command/Compile.php
src/RequirementChecker/AppRequirementsFactory.php
src/RequirementChecker/RequirementsDumper.php
tests/ConfigurationTest.php
tests/Console/Command/CompileTest.php
tests/PhpScoper/NullScoperTest.php
tests/RequirementChecker/AppRequirementsFactoryTest.php

When there is no dependencies Composer does not generate a `composer.lock` and as a result the
requirement checker could not be generated. This patch now allows to use the requirement checker
even in that situation.
Note however that this implies the requirement checker could be wrong if one has a `composer.json`
with dependencies but the `composer.lock` file went missing for some reasons. This is however and
edge case that I don't think Box should worry about.

Allow dumping requirements from the composer.json file

---

src/Console/Command/Compile.php
src/RequirementChecker/AppRequirementsFactory.php
src/RequirementChecker/RequirementsDumper.php
tests/RequirementChecker/AppRequirementsFactoryTest.php

The requirement checker was adding the `zip` extension as a requirement whenever the PHAR was
compressed. It is actually `zlib` if the compression is `Phar::GZ` and `bz2` if `Phar::BZ2`.

Fix the extension required when the PHAR is compressed

---

doc/configuration.md
src/Box.php
src/Composer/ComposerOrchestrator.php
src/Console/Command/Build.php
src/Console/Command/Compile.php
src/RequirementChecker/AppRequirementsFactory.php
src/functions.php
tests/BoxTest.php
tests/Console/Command/CompileTest.php

- Add a warning in the documentation and the logs of the `compile` command regarding the extension required to execute a PHAR once compressed
- Handle the compression in `Box` instead of using the leaked `Box#phar`
- Make `Box` countable
- A few minor refactoring bits
Closes #186

Fail gracefully when the extension required for the compression algorithm is not loaded

---

doc/configuration.md
doc/requirement-checker.md

Clarify the documentation regarding the dump-autoload setting

---

composer.lock
fixtures/build/dir010/scoper-fixed-prefix.inc.php
src/Configuration.php
tests/Console/Command/CompileTest.php

As per https://github.com/humbug/php-scoper/issues/178, it is possible to configure the prefix in PHP-Scoper in which case the prefix should be re-used here instead of always generating a random one.

Use PHP-Scoper prefix

---

doc/configuration.md
res/schema.json
src/Configuration.php
src/Console/Command/Build.php
src/Console/Command/Compile.php
src/PhpSettingsHandler.php
tests/ConfigurationFileTest.php
tests/ConfigurationTest.php
tests/ConfigurationTestCase.php
tests/Console/Command/CompileTest.php

Allow to disable the main script

---

src/Box.php
src/Compactor/Placeholder.php
src/Compactors.php
tests/Compactor/PlaceholderTest.php
tests/CompactorsTest.php

Add a new `Compactors` class which encapsulate a collection of `Compactor` instances and can apply all of them.
Also introduced a new `Placeholder` compactor: replacing the placeholders is now applying this
compactor instead of a separate dedicated step.

Refactor compactors

---

src/Console/Command/Compile.php

Fix invalid closure to bump the file descriptor

---

composer.json
composer.lock
doc/configuration.md
phpunit.xml.dist
src/Box.php
src/Configuration.php
src/ConfigurationLogger.php
src/Console/Command/Compile.php
src/functions.php
tests/BoxTest.php
tests/Compactor/ConfigurationLoggerTest.php
tests/ConfigurationSigningTest.php
tests/ConfigurationTest.php
tests/Console/Command/CompileTest.php

Related to #123.
The current implementation only adds the API at the `Configuration` level. Some TODOs have been changed as well in favour of that new system but I am certain there is more "recommendations" that could be added.
To completely close #123 more work needs to be done on the UI for the user to be able to read them.
Other notable changes:
- Add the Symfony PHPUnit bridge in order to notice the deprecation notice messages when running the tests
- Fail gracefully (i.e. with a meaningful message) when a wrong password has been provided to retrieve the private key necessary for OpenSSL signing
- Rename `isPrivateKeyPrompt()` to `promptPrivateKey()`. The old method is kept for BC but is marked as deprecated.
- Reworking the PHAR built-in signing part:
- An error is thrown if no path …

Add recommendations & warnings

---

src/RequirementChecker/RequirementsDumper.php
src/StubGenerator.php
tests/Console/Command/CompileTest.php
tests/RequirementChecker/RequirementsDumperTest.php
tests/StubGeneratorTest.php

Closes #253.
It seems there is an issue with the `.box/check_requirements.php` file because points to
`.box/bin/check-requirements` but without giving a prefix to the path. In any case that file looks
redundant so has been removed in favour of including `.box/bin/check-requirements.php` directly.

Remove unnecessary check_requirements.php file

---

src/Box.php
src/Console/Command/Compile.php
tests/Console/Command/CompileTest.php

- The file descriptor limit was being restored although it had not been changed
- The dumped content of the PHAR for debugging purposes was the content directly extracted from the PHAR. However, if the PHAR was being compressed, it was not uncompressing the dumped content causing the dumped files to appear as binaries. The PHAR content is now dumped before the PHAR is being compressed

Fixed dumping the PHAR contents and restoring the file limit

---

src/Console/Command/Process.php
tests/Console/Command/ProcessTest.php

When running the `process` command, the file path provided to the compactors was the absolute path whereas the `Box` class provides the relative path. This was causing issues with the PHP-Scoper
patchers since one will likely expect the relative path and not account for the path to be absolute.
To avoid extra unintuitive work to the user, the relative path is provided as during a regular
compilation.
When running the `process` command with a `quiet` verbosity, only the processed file contents will
be outputed. This allows one to easily copy the processed file contents.

Fix the processing of files

---

src/Console/Command/Command.php
src/Console/Command/ConfigurableCommand.php
src/Console/Command/Diff.php
src/Console/Command/Info.php
src/Console/Command/Validate.php
src/Console/Command/Verify.php
src/Console/ConfigurationLoader.php
tests/Console/Command/ValidateTest.php

No longer make `Validate` extend `ConfigurableCommand` since the configuration file is an argument
and the argument should be used instead of the option.
The validate command now properly takes the argument given instead of relying on the default find
found in the current working directory or the file passed via the configuration option.

Fix the validate command

---

fixtures/configuration/dir003/box.json
src/Configuration.php
tests/ConfigurationFileTest.php
tests/ConfigurationTest.php

- No longer display a message when the user force the `dump-autoload` setting to `true` when the result is that the autoloader cannot be dumped
- Skip dumping the autoloader when once of the `composer.lock` and `vendor/composer/installed.json` file is found but not the other
- Automatically append the composer files even when the auto-discovery is turned off to allow the
Composer autoloader to be dumped without issues
Closes #368.
Closes #359.

Fix the dump autoloader related issues

---

src/Console/Command/Diff.php
src/Pharaoh/PharDiff.php
src/Pharaoh/Pharaoh.php
tests/Console/Command/DiffTest.php

- Switch to custom classes to extend Pharaoh's behaviour
- Destroy the temporary directory created (cf. https://github.com/paragonie/pharaoh/issues/12)
- Replace the temporary file names used for the diff by the file basename for better readability
(https://github.com/paragonie/pharaoh/issues/13)

Implement various Pharaoh improvements

---

.travis.yml
.travis/install-ev.sh
.travis/install-event.sh
.travis/install-uv.sh
src/Configuration.php

Closes #380
- Deploy the scoped PHAR from the PHP 7.3 build instead of the 7.1
- Enable the suggested extensions for amphp to ensure the scoping doesn't scope the extension symbols by accident

Fix the scoping of Amphp

---

.php_cs.dist
Makefile
TODO
composer.json
composer.lock
scoper.inc.php
src/Composer/ComposerOrchestrator.php
tests/BoxTest.php
tests/Composer/ComposerOrchestratorTest.php
tests/Console/Command/CompileTest.php

Closes #398
- Fix how the Symfony environment variables are dumped (switch to `composer dump-env`)
- Use the user Composer executable instead of shipping one within Box

Fix the dump of Symfony environment variables

---

.gitignore
Makefile
TODO
fixtures/php-settings-checker/create-expected-output
fixtures/php-settings-checker/output-xdebug-enabled.tpl

The current PHP settings tests are a bit too flimsy since the xdebug version is explicitly expected in the output and that version may change.
This PR creates a new small bash script to fetch the xdebug version first and adjust the expected result accordingly.

Fetch the xdebug version

---

TODO
src/Box.php

When Box is not compiling by using `amphp/parallel`, the current error handler should not be changed.

Fix the change of error handler

---

Makefile
TODO
requirement-checker/scoper.inc.php

The requirement checker needs to be dumped whenever Box itself or the requirement checker changes. However as of now, the prefix used is random causing the git status to be constantly polluted by a newly dumped requirement checker.
In this PR, the prefix is constant but defined by the last release version which will fix the problem described above whilst ensuring each Box release will have a different requirement checker shipped.

Make the requirement checker dump deterministic

---

fixtures/php-settings-checker/output-all-clear
fixtures/php-settings-checker/output-min-memory-limit
fixtures/php-settings-checker/output-pharreadonly-enabled
fixtures/php-settings-checker/output-set-memory-limit
fixtures/php-settings-checker/output-xdebug-enabled.tpl
src/Console/Php/PhpSettingsHandler.php
tests/Console/Command/CompileTest.php

- No longer depends on the internal `Process::setEnv()` method
- Checks the memory limit only once (in the main process which is picked up by the sub-processes)

Simplify PhpSettings checker

---

Makefile
fixtures/php-settings-checker/output-pharreadonly-enabled
fixtures/php-settings-checker/output-xdebug-enabled.tpl
src/Console/Php/PhpSettingsHandler.php

Properly disable xdebug in the workers

---

composer.json

Fixes #439
(This is not yet a released version, so builds will naturally fail.)

Bump version requirement for json-schema

---

src/Console/Command/Compile.php
src/Console/Command/Extract.php
src/functions.php

Fix could not open stream due to too many files opened

---

src/Configuration/Configuration.php
tests/Configuration/ConfigurationTest.php

This resolves a problem when having the configuration file not within the repository itself (eg. in CI environments).
Now the configuration is using the `base-path` for running all git commands.
Fixes #465

Configuration::runGitCommand() now respects base-path

---

Makefile
composer.json
psalm.xml
vendor-bin/infection/composer.json

This change would permit to avoid conflicts when we will use PHPUnit 9.3

Move Infection to vendor-bin/

---

.travis.yml

Fix the Travis warnings:
`root`: deprecated key `sudo` (The key 'sudo' has no effect anymore.)
`deploy`: deprecated key `skip_cleanup` (not supported in dpl v2, use cleanup)
Example: https://travis-ci.org/github/box-project/box/builds/730694316/config#rccb_box:.travis.yml@e65178c5edaf5012.78
More info:
* https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release#:~:text=skip_cleanup%20is%20now%20deprecated%2C%20and,we%20have%20changed%20this%20default.

Fix Travis warnings

---

.gitignore
composer.lock
fixtures/build/dir012/composer.lock
fixtures/build/dir012/expected-output
fixtures/build/dir012/symfony.lock

@smoench I push the composer.lock I had on my machine since the last time I worked on Box. Hopefully the build should pass with it.

Add composer.lock

---

doc/configuration.md
src/Console/Command/Compile.php

In my projects I wanted a process that will build automatically (via composer) a fresh phar version as soon as my vendors changed.
And add also the corresponding manifest as metadata in phar file without to edit the `box.json.dist` file that accept only a hardcoded value.
This PR allow to use a custom callback.
See https://github.com/llaville/php-compatinfo-db/issues/59 my implementation with the custom callback (as example) and how I did all the automated process via composer.

Allows to use a callback as metadata producer

---

requirement-checker/phpunit.xml.dist
requirement-checker/src/Printer.php
requirement-checker/tests/PrinterTest.php

Fix OOM-Error in Printer::block

---

composer.json
composer.lock

This also allows us to bump the composer root version to 0.14.99 for php-scoper. Currently this is not possible as the caret version range is resolved as `>=0.13.10 <0.14.0` for pre-1.0 versions -> https://getcomposer.org/doc/articles/versions.md#caret-version-range-

update php-scoper to version 0.14

---

src/FileSystem/FileSystem.php

On Windows `FileSystem::remove` uses the native `rd` command (remove a directory) on all file system types, which obviously fails with something that is not a directory. Fixes #536

Fix FileSystem::remove with file on Windows

---

composer.json
composer.lock
fixtures/php-settings-checker/output-pharreadonly-enabled
fixtures/php-settings-checker/output-xdebug-enabled.tpl
src/Console/Php/PhpSettingsHandler.php

This adds support for Xdebug3 modes and changes the default behaviour from always restarting if Xdebug is loaded, to only restarting if Xdebug is active. 
Xdebug is considered active if it is loaded, and for Xdebug3, if it is running in a mode other than `xdebug.mode=off`.

Upgrade to xdebug-handler 2

---

src/Annotation/DocblockAnnotationParser.php
src/Annotation/MalformedTagException.php

Catch errors due to malformed tags

---

requirement-checker/src/RequirementCollection.php

A run on PHP 8.1 currently shows:
```
Deprecated: Return type of HumbugBox3100\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in path/to/.box/src/RequirementCollection.php on line 12
[php-scoper]
[php-scoper] Deprecated: Return type of HumbugBox3100\KevinGH\RequirementChecker\RequirementCollection::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in path/to/.box/src/RequirementCollection.php on line 16
```
These deprecation notices relate to the [Return types for internal methods …

PHP 8.1: fix two deprecation warnings

---

.github/workflows/build.yml

This commit adds running of the tests against PHP 8.1 to the GH Actions script.
Notes:
* As Composer v1 is not compatible with PHP 8.1 and, I suspect, will not be made compatible with PHP 8.1, PHP 8.1 cannot be added to the matrix array, but individual builds for PHP 8.1 (using Composer v2) have to be defined via `matrix:include`.
* As the PHPUnit Prophecy dependency does not yet allow for installation on PHP 8.1, the `composer install` for PHP 8.1 has to be special cased to use `--ignore-platform-reqs` (for the time being).
* As there are multiple dependencies of Box which have not yet released a PHP 8.1 compatible version, the builds against PHP 8.1 are allowed to fail via `continue-on-error` for now.
About the dependency failures:
* A PR has been opened against `nikic/iter` to fix the …

GH Actions: turn on testing against PHP 8.1

---

.requirement-checker/src/RequirementCollection.php

It looks like https://github.com/box-project/box/pull/557 wasn't enough to fix this. This file needs updating too.

Fixed PHP 8.1 compatibility of the requirement checker

---

composer.json
composer.lock
src/Console/Php/PhpSettingsHandler.php

composer/xdebug-handler version 3 provides the same functionality as version 2 but removes support for older PHP versions (< 7.2.25). It will be shipped with the impending Composer 2.3 release.
xdebug-handler version 2 will be supported for the lifetime of [Composer 2.2 LTS](https://blog.packagist.com/composer-2-2/).

Add xdebug-handler version 3

---

scoper.inc.php

This PR resolves this issue around PHAR compilation:
```
PHP Fatal error:  Uncaught Error: Call to undefined function _HumbugBox48cf944fc33a\Symfony\Component\Console\get_debug_type()
```
The solution used is using a similar approach to https://github.com/humbug/php-scoper/pull/481
Resolves #550

exclude symfony polyfills from php scoper during PHAR compilation

---

src/Amp/FailureCollector.php
src/Console/Command/Compile.php

There was two issues before:
- We were giving `$io->error($throwableInstance)` which is really not clear how it should be handled and will likely result in a failure in the future
- Printing reach reasons.
The 2nd point is especially bad when the source of the failure is common. In this situation you will get as many reasons as workers fired up resulting a lot of identical reasons printed over and over.
In this PR:
- we pass the reason (string) to the IO
- we collect all the reasons beforehand to remove the duplicates
- add a message to help the user to diagnose the issue

Improve AMP error handling.

---

requirement-checker/scoper.inc.php

- The `expose-global-*` settings are by default at `false`
- `sapi_windows_vt100_support` is not correctly part of JetBrains' stubs

Update the requirement checker config

---

.github/workflows/build.yaml
.github/workflows/e2e-tests.yaml
.github/workflows/lint.yaml
.github/workflows/unit-tests.yaml

A number of predefined actions have had major release, which warrant an update to the workflow(s).
These updates don't actually contain any changed functionality, they are mostly just a change of the Node version used by the action itself (from Node 14 to Node 16).
Refs:
* https://github.com/actions/checkout/releases
* https://github.com/actions/download-artifact/releases
* https://github.com/actions/upload-artifact/releases

GH Actions: version update for various predefined actions

---

.github/workflows/build.yaml
.github/workflows/e2e-tests.yaml
.github/workflows/unit-tests.yaml

The action used to install Composer packages and handle the caching has released a new major (and some follow-up patch releases), which means, the action reference needs to be updated to benefit from it.
Note: v2 is a complete rewrite of the action.
Refs:
* https://github.com/ramsey/composer-install/releases/

GH Actions: version update for `ramsey/composer-install`

---

Makefile

Since this is the default on a PHP install it is best to make it easier.

Fix generation of stubs if phar.readonly is enabled

---

fixtures/Console/Command/TestConfigurableCommand.php
src/Configuration/ConfigurationLoader.php
src/Console/Application.php
src/Console/Command/BaseCommand.php
src/Console/Command/ConfigurableBaseCommand.php
src/Console/Command/Validate.php
src/Console/ConfigurationLoader.php
src/Console/ConfigurationLocator.php
tests/Composer/ComposerOrchestratorTest.php
tests/Configuration/ConfigurationLoaderTest.php
tests/Configuration/ConfigurationTestCase.php
tests/Console/ConfigurationLocatorTest.php

The current configuration helper has several drawbacks:
- It does several things: loading the config & locating the config
- Is a "fake service" – a special console helper
In this PR:
- The locating part of `ConfigurationHelper` is extracted into a dedicated `ConfigurationLocator` class
- The remaining part of `ConfigurationHelper` has been renamed to `ConfigurationLoader` and no longer extends `Helper`

Rework configuration helper

---

src/Console/Command/Compile.php
tests/Console/Command/CompileTest.php

Extracted from #646 
- Make methods static when possible
- Compare to the count rather than an empty array
- Avoid having an assignment in an if close
- Remove unnecessary dependency of `Command::getApplication()` e.g. when getting the logo

Refactor Compile command

---

src/Console/Command/Validate.php

Review the validate command

---

composer.json
composer.lock

While updating a workflow to use Box 4.x, I noticed that the branch alias hadn't been updated.
Might also be worth it to mention in the changelog that the `sodium` extension is now a non-dev requirement for running Box (under BC-break).
The entry as-it-is under `Misc` was the reason for me to check the `composer.json` of the file to see what was required as an alternative, only to realize that the extension is now required.
[Edited]: the original PR also removed the `replace` command, but I now see why that was put in place.

Composer: minor tweaks

---

.gitignore
doc/assets/announce.css
mkdocs.yaml

Minor fixes on documentation site, according to new version of [mkdocs-material](https://squidfunk.github.io/mkdocs-material/) theme.
-  In `mkdocs.yaml`, add `scheme: default` option, which now is mandatory.
- Adjust `doc/assets/announce.css` since the class applied to the announce bar now is `md-banner`, instead of `md-announce`

Fix documentation site

---

src/functions.php

When `humbug/box` is installed via Composer then
```php
require_once __DIR__.'/../vendor/composer/InstalledVersions.php';
```
(from https://github.com/box-project/box/blob/4.0.2/src/functions.php#L61)
fails as this files exist only when is used as PHAR.
Current behaviour can be seen in the failing check in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6554.

Fix for Composer installation

---

res/schema.json
tests/DocumentationSchemaTest.php

Adding `{"$schema": "vendor/humbug/box/res/schema.json"}` to the config file allows PhpStorm to provide completions. However, the `$schema` key is reported as not allowed.

Allow `$schema` in JSON schema

---

doc/installation.md

Even though the instructions work right now (because Github redirects to the correct URL), it may be more reflective of the Github username to update the URL in the brew tap command.

Update homebrew installation instructions

---

Makefile

I think there is some serious issues, either related to amphp or laravel/closure. In any case currently I see a x1000 speed difference...

Do not compile in parallel

---

.github/workflows/release.yaml

- Rename the workflow from "build" to "release" to match PHP-Scoper.
- In-line the PHP version to no longer have the title changing with the PHP version used.

ci: Refactor the release workflow

---

Makefile
bin/generate_default_stub
tests/Console/Command/CompileTest.php

- Move the generated stub to the `dist` directory
- Fix the Makefile target which was making the stub a PHONY target (it is not)

chore: Fix default stub generation

---

Makefile

- Simplify the rule for generating the coverage
- Fix the timestamp detection to not re-generate the coverage when running `make _infection` or `make infection_ci`

chore(makefile): Fix the coverage generation

---

.github/workflows/e2e-tests.yaml
composer.json
composer.lock
requirement-checker/composer.json
requirement-checker/composer.lock
requirement-checker/tests/AutoReview/E2EMakefileTest.php
requirement-checker/tests/AutoReview/GAE2ECollector.php
requirement-checker/tests/AutoReview/GAE2ECollectorTest.php
requirement-checker/tests/AutoReview/GAE2ETest.php
requirement-checker/tests/AutoReview/MakefileE2ECollector.php
tests/AutoReview/E2EMakefileTest.php
tests/AutoReview/GAE2ECollector.php
tests/AutoReview/GAE2ECollectorTest.php
tests/AutoReview/GAE2ETest.php
tests/AutoReview/MakefileE2ECollector.php

We already have tests to ensure the e2e Makefile target executes all the known e2e target, but we were missing a similar check for GitHub Actions.

build: Add auto-review tests to ensure the E2E tests are in sync with  the GitHub Actions config

---

composer.json
src/Compactor/Php.php
src/Configuration/Configuration.php
tests/Annotation/DocblockAnnotationParserTest.php
tests/Compactor/PhpTest.php
tests/Configuration/ConfigurationPhpCompactorTest.php

fix: Correctly disable the annotation compacting when configuring `annotations=false`

---

requirement-checker/fixtures/fail-complete/expected-boxmin-stderr.dist
requirement-checker/fixtures/fail-complete/expected-composermin-stderr.dist
requirement-checker/fixtures/pass-complete/expected-boxmin-stderr.dist
requirement-checker/fixtures/pass-complete/expected-composermin-stderr.dist
src/RequirementChecker/AppRequirementsFactory.php
tests/RequirementChecker/AppRequirementsFactoryTest.php
tests/RequirementChecker/RequirementsDumperTest.php

fix(requirement-checker): Rephrase incorrect message for the PHP constraint

---

src/Configuration/Configuration.php
src/Configuration/ExportableConfiguration.php
tests/Configuration/ConfigurationTest.php
tests/Console/Command/CompileTest.php

Create a dedicated class for exporting the Configuration. This allows two things:
- Trim down a bit `Configuration` which is already quite big
- Have better type-safety since the types desired for the exported configuration differ from the regular configuration and having them in one means widening those types making the usage less type-safe.

refactor: Simplify the exported configuration

---

src/Configuration/Configuration.php
tests/Configuration/ConfigurationTest.php

In some older versions of Composer the `composer.lock` file was not always generated. It is now, at the very least since 2.2, always generated.
Since the `composer.json` information is too lacking to provide a reliable result for the requirement checker (it does not contain the information about each package, hence what the packages requirements are or what extension they provide cannot be known), I want to deprecate using the requirement checker when the `composer.lock` file is not found.

feat: Deprecate explicitely enabling the requirement checker when the composer.lock could not be found.

---

src/RequirementChecker/AppRequirementsFactory.php
tests/RequirementChecker/AppRequirementsFactoryTest.php

As explained in #867, the `composer.json` provides only partial and incomplete information which is why it is preferable to use the `composer.lock` file instead.

fix: Use information from the composer.lock when possible for the requirement checker

---

src/RequirementChecker/AppRequirementsFactory.php
src/RequirementChecker/PackageInfo.php
tests/RequirementChecker/PackageInfoTest.php

When we have access to a package info in a `composer.lock`, which extension a package may polyfill can be found in the `provide` section. This is much more reliable than trying to guess it from some package conventions like the Symfony polyfills or manually map some other popular polyfills.
The previous way of doing it kept for now, in case we fall back to the `composer.json`, but it will disappear as soon as we no longer support inferring the requirements from the `composer.json` file in 5.0.

fix: Take the polyfilled extensions from the "provide" package info

---

requirement-checker/src/Checker.php
res/requirement-checker/src/Checker.php
src/RequirementChecker/AppRequirementsFactory.php
src/RequirementChecker/Requirement.php
tests/RequirementChecker/AppRequirementsFactoryTest.php
tests/RequirementChecker/DecodedComposerJsonTest.php
tests/RequirementChecker/RequirementTest.php

Minor refactoring to prepare for #872.

refactor: Refactor elements of the requirement checker

---

requirement-checker/fixtures/fail-complete/expected-boxmin-stderr.dist
requirement-checker/fixtures/fail-complete/expected-composermin-stderr.dist
requirement-checker/fixtures/fail-conflict/expected-boxmin-stderr.dist
requirement-checker/fixtures/pass-complete/expected-boxmin-stderr.dist
requirement-checker/fixtures/pass-complete/expected-composermin-stderr.dist
requirement-checker/src/Checker.php
requirement-checker/src/Printer.php
requirement-checker/tests/CheckerTest.php
requirement-checker/tests/PrinterTest.php
res/requirement-checker/src/Checker.php
res/requirement-checker/src/Printer.php

- When printing the constraint checked, the message shown should be the requirement message.
- When priting the recommendations, the message shown should be the failed requirements *help* message.
The current final output now makes no sense (it is inversed), but this is because the messages set upstream are incorrect and they will be fixed separately.

fix(requirement-checker): Fix the constraint message displayed

---

.github/workflows/release.yaml

- Publish the homebrew formula in a different dedicated step
- Use a dedicated access token for updating the homebrew formula
- Fix the name of Docker publish job
- Fix the access to the PHAR within the Docker publish job

ci: fix the release

---

.github/workflows/requirement-checker.yaml

Due to the git reference changing all the time, we always get a change for the requirement checker resulting in a PR being made.

ci: Ensure the requirement checker references are not changing

---

composer.json
composer.lock
tests/Compactor/PhpTest.php

With the update of `phpdocumentor/type-resolver` 1.7.0, a peculiar case is no longer broken.

fix: Fix the parsing of invalid PHPDoc

---

tests/Console/Command/ExtractTest.php

Refactor `ExtractTest` to better accommodate the upcoming changes.

test: Refactor ExtractTest

---

src/Console/Command/Extract.php
tests/Console/Command/ExtractTest.php

Simply throw the exception rather than handling it to write the error our own way.

refactor: Simplify the error handling of Extract

---

src/Console/Command/Extract.php
tests/Console/Command/ExtractTest.php

Remove the usage of `Box` or `Pharaoh`. This currently creates some redundancy with the implementation of `Pharaoh`, but the latter will be refactored to leverage the extract command instead of the other way around.

refactor: Directly dump the PHAR content in the Extract command

---

src/Console/Command/Extract.php
tests/Console/Command/ExtractTest.php

Introduce the option `--internal` to the extract command. There is a number of changes with the introduction of this option:
- Instead of basing the default value to the question of whether the target dir should be deleted or not, it is now done based in this flag
- When this flag is passed, the error thrown when creating the PHAR is swallowed and its message written to the STDERR. This will allow to retrieve it in Pharaoh when executing it without having the whole stack trace.

feat: Add an internal option to the extract command

---

src/Console/PharInfoRenderer.php
tests/Console/Command/InfoTest.php

The file PHAR size shown previously was the one from the temporary PHAR created which may differ in size (for example because we change the alias).

fix: File the PHAR file size shown

---

tests/Console/Command/InfoTest.php

This tests is giving me headaches and I don't really want to address it at the moment.

test: Disable InfoTest in the CI

---

Makefile
requirement-checker/Makefile

Currently the make command fails because the `bin/sh` shell used does not handle ANSI escape codes for the colour formatting.
Instead, we use `$(shell ...)` functions to execute a command that produces the ANSI escape codes.

build: Use more portable colours

---

.github/workflows/auto-review.yaml
.github/workflows/docker.yaml
.github/workflows/e2e-tests.yaml
.github/workflows/gh-pages.yaml
.github/workflows/release.yaml
.github/workflows/requirement-checker.yaml
.github/workflows/security.yaml
.github/workflows/unit-tests.yaml

Currently when merging a couple of PRs the CI is having a meltdown. This is an attempt to reduce the load.

ci: Add a concurrency strategy

---

tests/Phar/PharFactoryTest.php

Revert #1024: the actual issue is about whether the phar.readonly is on or off rather than the PHP version.

test: Fix PharFactoryTest

---

Makefile.e2e

Without the platform the output is:
```
docker run --interactive --pull=never --rm local_box_e2e_dockerfile:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Everything is fine! The extension XML is loaded.
```
Which messes up the `diff` output tests.

build: Fix docker run command on OSX M1

---

.github/workflows/docker.yaml
.github/workflows/e2e-tests.yaml
.github/workflows/gh-pages.yaml
.github/workflows/release.yaml
.github/workflows/security.yaml
.github/workflows/unit-tests.yaml

Rather than cherry-pick to try to guess where this is needed and find cases like https://github.com/box-project/box/actions/runs/6439968179/job/17488273402?pr=1029 I prefer to apply it everywhere.

ci: Add the XTERM variable to all workflows

---

src/Box.php
src/Console/Command/Diff.php
src/Console/Command/Info.php
src/Console/Command/Verify.php
src/Console/PharInfoRenderer.php
src/Phar/PharDiff.php
src/Phar/PharInfo.php
tests/Phar/PharInfoTest.php

After reviewing the usages I think PharInfo is more descriptive than SafePhar.

refactor: Rename SafePhar into PharInfo

---

src/Console/Command/Diff.php
tests/Console/Command/DiffTest.php

- Restarting the process is no longer needed within the diff command as extracting the PHAR is done in a separate process.
- Catching the exception is no longer necessary or desired since any failure will throw a comprehensive error.

fix: Remove unnecessary code from the diff command

---

tests/Console/Command/GenerateDockerFileTest.php
tests/Console/Command/InfoTest.php
tests/Console/Command/ValidateTest.php
tests/Phar/PharFactoryTest.php
tests/Phar/PharInfoTest.php

Since PharInfo ensures a memory-safe consumption of the PHAR, some tests no longer need to be executed in separate processes.

test: Remove unnecessary separate processes annotation

---

tests/Console/Command/DiffTest.php

test: Simplify usage of realpath in DiffTest

---

src/Console/Command/Diff.php
tests/Console/Command/DiffTest.php

Now that the equality check works as expected (see #1049), we can simplify the way the diff command works by checking the equality once and skip the "archive" and "content" comparisons if the archives are equal.

feat: Simplify the diff command comparison

---

composer.json
composer.lock
src/Console/Command/Diff.php
src/Phar/PharDiff.php
tests/Console/Command/DiffTest.php

- Always display a summary of both archives upon equality failure.
- Provide a human-readable diff of the archives when possible.
- Make the message more explicit that if no diff was found for the archives content, this is true for the selected diff mode, i.e. a difference may be found with another diff mode.

feat: Rework the diff command output

---

src/Console/Command/Diff.php

Now that the checksum is a lot easier to do than before, I think it makes more sense to pick it as the default diff mode.
It will not be as easily understandable than GNU or Git, but will show the problematic files whilst being more available than the GNU/git diff modes.

feat: Change from filename to checksum as the default diff mode

---

src/Composer/ComposerOrchestrator.php
tests/Console/Command/CompileTest.php

I suspect in some context the current `ComposerOrchestrator::getVersion()` could get the ANSI output for which the regex we use afterwards to extract the Composer version does not work. Rather than fixing the regex which is not trivial, it makes more sense to guarantee a no-ANSI output.
Fixes #1004.

fix: Get the raw output for the Composer version

---

src/PharInfo/PharInfo.php

fix: Add back the old PharInfo

---

tests/Console/ApplicationTest.php
tests/Console/Command/CompileTest.php
tests/Console/DisplayNormalizer.php

Pick a non-existent generic version instead of an outdated one to avoid any confusion.
Closes #928.

test: Update the fake Box version used

---

doc/configuration.md

Closes #945.
I originally wanted to add a warning or recommendation in the configuration but there is a few projects consciously using this feature and it does not feel right to add a warning for them in this scenario.

doc: Clarify the behaviour when using both directories and finder

---

src/Console/Command/Diff.php

Previously this was resulting in a FatalError with an obscure message.

fix: Make the invalid diff mode error message understandable

---

src/Composer/ComposerOrchestrator.php

The goal here is to make this piece re-usable. In the end Box only cares about the autoload but from a user (for debugging purposes) perspective, the vendor directory is what we want.

refactor: Expose ComposerOrchestrator getVendorDir

---

src/Composer/ComposerOrchestrator.php
src/Composer/ComposerProcessFactory.php
tests/Composer/ComposerOrchestratorTest.php

In the case the output is polluted by deprecation messages or other, Box could not figure out the Composer version.

fix: Correct detect the Composer version with a polluted output

---

composer.json
composer.lock

- `ext-mbstring` is required and to allow it to work as a PHAR the polyfill is added.
- `symfony/polyfill-mbstring` require `iconv` (see https://github.com/symfony/symfony/issues/52207).

fix: Require missing iconv and mbstring dependencies

---

src/Composer/ComposerProcessFactory.php
src/Console/Php/PhpSettingsHandler.php

- Use the persistent setting: any sub-process should use the same settings.
- Reset `COMPOSER_ORIGINAL_INIS` to avoid the buggy Flex code (see https://github.com/symfony/flex/pull/995).
Closes #1089, #988.

fix: Ensure the PHP processes are restarted properly

---

src/Configuration/Configuration.php
tests/Configuration/ConfigurationSigningTest.php
tests/Console/Command/CompileTest.php

feat: Deprecate OpenSSL signing

---

composer.lock

Trying to run tests locally using PHP 8.2 results in a bunch of errors, including:
> Creation of dynamic property PHPUnit\Framework\ExpectationFailedException::$xdebug_message is deprecated in /Users/dane.powell/src/box-project/box/vendor/phpunit/phpunit/src/Util/PHP/AbstractPhpProcess.php:289
Updating phpunit fixes this. There are several other outdated dependencies so I did a general `composer update`. Let me know if you're interested in setting up Dependabot to keep dependencies updated automatically.

Run tests in PHP 8.2

---

tests/Phar/PharMetaTest.php
tests/bootstrap.php

I'll admit I don't quite understand why this is failing, but I'm guessing no one has actually run tests on macOS recently and this broke sometime along the way.

Fix tests on macOS

---

src/Console/Command/Process.php
tests/Console/Command/ProcessTest.php

The term "whitelist" is no longer correct.

fix: Fix the process command whitelist term

---

README.md
doc/installation.md

The other methods are now preferred and downloading via the GitHub release has a new doc entry (`#github`) which contains more detailed steps.

doc: Remove installation doc entry for PHAR

---

src/Box.php
src/Console/Command/Compile.php
tests/BoxTest.php

The `Phar` instance might be unset within `Box` hence it should not be leaked to any production code.

refactor: Make Box::getPhar() internal

---

.github/workflows/release.yaml

See https://github.com/humbug/php-scoper/pull/923.

ci: Fix the release workflow permissions

---

src/Console/Command/Compile.php

Fixes a replacement missed in #1184.

fix: Fix invalid usage of non-existing constant

---

.github/workflows/requirement-checker.yaml

This task now requires explicit write permissions for pull requests.

ci: Fix the requirement checker PR creation

---

.github/workflows/benchmark-empty.yaml
.github/workflows/benchmark.yaml
bin/bench-test.php
fixtures/bench/with-compactors/box.json.dist
fixtures/bench/with-compactors/res/requirement-checker/bin/check-requirements.php
fixtures/bench/with-compactors/res/requirement-checker/src/Checker.php
fixtures/bench/with-compactors/res/requirement-checker/src/IO.php
fixtures/bench/with-compactors/res/requirement-checker/src/IsExtensionConflictFulfilled.php
fixtures/bench/with-compactors/res/requirement-checker/src/IsExtensionFulfilled.php
fixtures/bench/with-compactors/res/requirement-checker/src/IsFulfilled.php
fixtures/bench/with-compactors/res/requirement-checker/src/IsPhpVersionFulfilled.php
fixtures/bench/with-compactors/res/requirement-checker/src/Printer.php
fixtures/bench/with-compactors/res/requirement-checker/src/Requirement.php
fixtures/bench/with-compactors/res/requirement-checker/src/RequirementCollection.php
fixtures/bench/with-compactors/res/requirement-checker/src/Terminal.php
fixtures/bench/with-compactors/res/schema.json
fixtures/bench/without-compactors/box.json.dist
fixtures/bench/without-compactors/res/requirement-checker/bin/check-requirements.php
fixtures/bench/without-compactors/res/requirement-checker/src/Checker.php
fixtures/bench/without-compactors/res/requirement-checker/src/IO.php
fixtures/bench/without-compactors/res/requirement-checker/src/IsExtensionConflictFulfilled.php
fixtures/bench/without-compactors/res/requirement-checker/src/IsExtensionFulfilled.php
fixtures/bench/without-compactors/res/requirement-checker/src/IsFulfilled.php
fixtures/bench/without-compactors/res/requirement-checker/src/IsPhpVersionFulfilled.php
fixtures/bench/without-compactors/res/requirement-checker/src/Printer.php
fixtures/bench/without-compactors/res/requirement-checker/src/Requirement.php
fixtures/bench/without-compactors/res/requirement-checker/src/RequirementCollection.php
fixtures/bench/without-compactors/res/requirement-checker/src/Terminal.php
fixtures/bench/without-compactors/res/schema.json

Follow up of #1204 which required to have a workflow landing in `main`.
This PR:
- Moves the `res` directory included for the benchmarked code to avoid potential FS issues.
- Run another job: the PHPBench for the PR, without comparing with `main`, to have some feedback in case the PHPBench in `main` fails.
- Do not fail if the performance target is not met: this is work for the future.

build: Fix PHPBench workflow

---

.github/workflows/benchmark.yaml
.github/workflows/docs-empty.yaml
.github/workflows/docs.yaml

- Remove `empty-benchmark.yaml`: it is not needed as the rule for required workflows apply to pull requests only.
- Rename `GitHub-Pages` to `Docs`.
- Introduce the `docs-empty.yaml` analogue to `empty-benchmark.yaml` prior to its removal.

ci: Fix conditional required workflows

---

.github/workflows/benchmark.yaml

To enable back once generating the report file is figured out.

ci: Disable the PR-main benchmark comparison

---

bin/bench-test.php

The benchmark in the CI is not stable enough so allowing poorer performances to not make the build fail.

perf: Lower the target from 75% to 80%

---

bin/bench-test.php

Since GitHub Actions has a very limited amount of cores (2 most of the time), the benefits brought by the parallelization are very limited hence to avoid having the pipeline all the time red it should be made more flexibile.

test(perf): Reduce the benchmark requirements

---

tests/Benchmark/AppRequirementFactoryBench.php

Creating the `ComposerJson` and `ComposerLock` files are not exactly free given that they have an IO operation. Hence, it makes more sense to move their instantiation to the setup method to reduce the noise from the actual benchmark.

test(perf): Remove noise from AppRequirementFactoryBench

---

src/RequirementChecker/RequirementsBuilder.php

- Move sorting the extensions into a dedicated explicit method for better re-usability.
- Provide directly the whole sorted data set rather than a partially sorted one.

refactor: Simplify the sorting in the requirement builder

---

src/RequirementChecker/AppRequirementsFactory.php
src/RequirementChecker/Requirement.php
src/RequirementChecker/RequirementType.php
src/RequirementChecker/RequirementsBuilder.php
tests/RequirementChecker/RequirementTest.php
tests/RequirementChecker/RequirementsBuilderTest.php

This is a preparatory step for #1273. The goal is to be able to provide _all_ the requirements. The idea being that one may be interested in seeing this full list for debugging purpose, rather than the strict final one where the provided extensions removed the required extensions from the calculated requirements.

feat: Provide a non optimized requirement list

---

src/RequirementChecker/RequirementsBuilder.php
tests/RequirementChecker/RequirementsBuilderTest.php

Instead of first dividing by category (required or provided) and then by source, we no longer devide by category.
This allows to better inspect what the status is for a given extension with the `info:requirements` command (see !1273).

feat: Group by source the required and provided extensions

---

composer.lock
fixtures/php-settings-checker/expected-stdout-phar-readonly-enabled
fixtures/php-settings-checker/expected-stdout-xdebug-enabled.tpl

Updates `composer/xdebug-handler` from 3.0.3 to 3.0.4
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/composer/xdebug-handler/releases">composer/xdebug-handler's releases</a>.</em></p>
<blockquote>
<h2>3.0.4</h2>
<ul>
<li>Added: Functional tests.</li>
<li>Fixed: Incompatibility with PHPUnit 10.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/composer/xdebug-handler/blob/main/CHANGELOG.md">composer/xdebug-handler's changelog</a>.</em></p>
<blockquote>
<h2>[3.0.4] - 2024-03-26</h2>
<ul>
<li>Added: Functional tests.</li>
<li>Fixed: Incompatibility with PHPUnit 10.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a …

build(deps): Update composer/xdebug-handler

---

composer.json
tests/Console/Command/CompileCommandTest.php

For some reasons (not entirely sure why tbh), we end up with `composer.phar` in the CI resulting in a different path than the one expected.

test: Fix composer path

---

doc/configuration.md

The link was handled by `symfony.com` thanks to their redirect but lychee did not appreciate the redirects in the CI. We should use the correct link in the first place though.

docs: Fix link redirection

---

composer.json
composer.lock

`marc-mabe/php-enum` is not used by Box directly but required by `justinrainbow/json-schema` (which is a box dependency). But outdated versions trigger warnings in PHP 8.2+.

build: Bump the minimum version of marc-mabe/php-enum used
